default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Caleb526
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: rugby_app_backend

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

